[19기 문희원] Add : GET ArtDetailView
wecode-bootcamp-korea/19-2nd-Younggulart-backend pull request #10
Opened 2021-05-01 07:17 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 작품 상세 페이지 보기 기능 구현
		 
## 수정 사항들 자세한 내용
- 작품 id path parameter로 받습니다.
- 유닛테스트 success, not found 두 가지 상황 완료했습니다.
<img width="996" alt="Screen Shot 2021-05-01 at 4 13 35 PM" src="https://user-images.githubusercontent.com/63729090/116774537-31ab6880-aa98-11eb-8c0d-387a51b7d823.png">

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-02 14:44 UTC, Kang-kyunghun requested changes

2021-05-02 14:44 UTC, Kang-kyunghun commented on arts/arts_views.py
> +        art_id = art_id
매개변수로 art_id를 받기 때문에 다시 선언 안 해도 괜찮습니다.

2021-05-02 14:44 UTC, Kang-kyunghun commented on arts/arts_views.py
> +                image.image_url for image in art.artimage_set.all()
혹시 이 부분에서 prefetch_related와 상관없이 다시 쿼리가 증가 하나요? 만약에 증가 한다면,  Prefetch object에 대해 알아보고 적용하면 좋을 것 같습니다.

2021-05-02 14:44 UTC, Kang-kyunghun commented on arts/arts_views.py
> +        if not art:
존재 여부만 판단하는 것이므로 .exists()을 붙여주는 것이 좋을 것 같습니다.

2021-05-02 15:37 UTC, moonimooni commented on arts/arts_views.py
> +        if not art:
경훈님 .exists()로 존재여부 판단 후 get(id=art_id)를 쓰는 것보다 .first()로 객체 반환 후 if not art 를 쓰는 방법이 쿼리수도 적은데 exists() 메소드를 쓰는 이유는 코드의 명시성을 위해서인가요?

2021-05-02 16:08 UTC, Kang-kyunghun requested changes

2021-05-02 16:08 UTC, Kang-kyunghun commented on arts/arts_views.py
> +        if not art:
일단 .first() 부분은 제가 놓쳤네요.
.exist()을 사용하는 이유는 명시적인 이유보다는 조금 더 효과적으로 쿼리를 사용하기 위해서 입니다. filter.first()를 하게 되면 filter에 의해 해당 테이블의 모든 필드 데이터를 가져오려고 하고 .exists()는 진짜 존재 여부만 판단 하는 쿼리를 날리게 됩니다. 위와 같은 상황에서는 정확히 하기 위해서는 load test를 한 번 해보면 좋을 것 같아요.

2021-05-02 16:46 UTC, moonimooni commented on arts/arts_views.py
> +                image.image_url for image in art.artimage_set.all()
아 경훈님 제가 바보같이... 이미지 하나만 넣어놓고 테스트해서 차이가 별로 없는거였습니다 ^0^;;;;; 이미지 좀 넣어놓고 테스트해보니 문제없습니다!

2021-05-02 17:24 UTC, moonimooni commented on arts/arts_views.py
> +        if not art:
어렵네요...

.filter().first()도 SQL문으로 보면 ```SELECT #조건 생략# ORDER BY `id` ASC LIMIT 1;``` 인데

.exists()로 존재여부 판단 뒤 .get() 하는것도 결국엔 ```SELECT (1)``` 한 다음에 
```SELECT #조건 생략# LIMIT 21;``` 과정을 똑같이 거쳐야 해서 filter().first()를 선택했습니다.
(왜 LIMIT이 21이 찍히는지는 모르겠습니다)

만약 존재하지 않는 art_id라면 .exists() 코드가 메모리 효율성도 더 좋고 빠르겠지만, 
이미 저희 application은 프론트단에서 이미 한 번 검증해준 id값이 들어오기 때문에 
보통 존재하는 art_id가 들어온다는 상황을 가정하고 코드를 작성했습니다.

2021-05-02 17:30 UTC, moonimooni commented
일단 필요한 select_related 좀 더 추가해서 다시 커밋 작성했습니다~! 쿼리 로그 수도 확연하게 줄었습니다.

2021-05-03 01:29 UTC, Kang-kyunghun requested changes

2021-05-03 01:29 UTC, Kang-kyunghun commented on arts/arts_views.py
> +            .select_related('material') \
```suggestion
            .select_related('artist', 'status', 'paper') \
            .select_related('material') \
```
이렇게 한 번에 쓸 수도 있습니다~

2021-05-03 01:29 UTC, Kang-kyunghun commented on arts/arts_views.py
> +        if not art:
- 확실히 효율적인 측면에서 많이 고민이 되게 하는 부분이네요. 그렇다면 다른 사람들이 이 코드를 봤을 때 더 명확하게 코드를 이해 할 수 있도록 짜는 것을 더 추천합니다. (논리적으로 맞게 코드가 구성되어 있어 굳이 지금 코드에서 바꿀 필요는 없습니다.) 
- 당연히 프론트에서 데이터를 줄 때는 알고 있는 값을 줄 것입니다. 그러나 api 측면에서 봤을 때는 아는 값이 보장 된다고 생각 할 수는 없을 것 같아요. 당연히 아는 값이 들어 온다면, 예외 처리를 안 해도 되지 않을까요?
- https://www.reddit.com/r/django/comments/6plqbn/advice_to_get_single_object_using_get_or/ 이 링크도 한 번 참고 하면 좋을 것 같아요

2021-05-03 02:34 UTC, moonimooni commented on arts/arts_views.py
> +            .select_related('material') \
오오 수정하겠습니다

2021-05-03 03:51 UTC, moonimooni commented on arts/arts_views.py
> +        if not art:
흠... api는 보장된 값을 고려하지 않는다 생각하면... exists()로 한 번 거치는 게 더 낫겠다는 생각이 드네요! 좋은 의견 감사드립니다 ><

2021-05-03 15:32 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-03 15:32 UTC, merged