[19기 문희원] Add : GET BiddingView
wecode-bootcamp-korea/19-2nd-Younggulart-backend pull request #13
Opened 2021-05-04 04:54 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 현재 입찰 진행중인 작품

## 수정 사항들 자세한 내용
- 입찰이 곧 끝날 예정인 작품 순으로 리스트 나열됩니다.
<img width="669" alt="Screen Shot 2021-05-04 at 1 54 24 PM" src="https://user-images.githubusercontent.com/63729090/116962169-3e220200-ace0-11eb-9c48-ef5d120f47bb.png">

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-04 09:57 UTC, redsaumon commented
conflict 수정해주세요~

2021-05-04 11:26 UTC, moonimooni commented
> conflict 수정해주세요~

해결했습니다~!

2021-05-05 11:31 UTC, Kang-kyunghun requested changes

2021-05-05 11:31 UTC, Kang-kyunghun commented on bids/views.py
> +                'id' : bidding.art.id,
:에 맞춰 정렬해 주세요.

2021-05-05 11:41 UTC, moonimooni commented on bids/views.py
> +                'id' : bidding.art.id,
넹 수정했습니다~

2021-05-05 15:34 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-05 15:34 UTC, merged