[19기 서득영][Add]Frame GET api 구현
wecode-bootcamp-korea/19-2nd-Younggulart-backend pull request #16
Opened 2021-05-04 12:20 UTC by ulr0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Frame GET api 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- FrameView 생성
- urls.py path 설정
- 유닛테스트 실행
![image](https://user-images.githubusercontent.com/78151345/117002417-7fd19d80-ad1e-11eb-908f-103ee743a9bd.png)
![image](https://user-images.githubusercontent.com/78151345/117002435-83fdbb00-ad1e-11eb-9381-17434b474fea.png)
![image](https://user-images.githubusercontent.com/78151345/117002439-85c77e80-ad1e-11eb-83df-de39253cadcf.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-05-05 11:35 UTC, Kang-kyunghun requested changes

2021-05-05 11:35 UTC, Kang-kyunghun commented on orders/tests.py
> +            })
id가 존재하지 않을 때 예외처리 구현 하셨던데 그것도 테스트 코드에 추가해 주세요.

2021-05-05 11:35 UTC, Kang-kyunghun commented on orders/views.py
> +                            - (art.height_cm * art.width_cm)) * frame.price_rise_rate * 100
가격 계산하는 부분 lambda로 고쳐보면 어떨까요?

2021-05-05 11:46 UTC, ulr0 commented on orders/tests.py
> +            })
넵 추가했어요

2021-05-05 12:01 UTC, ulr0 commented on orders/views.py
> +                            - (art.height_cm * art.width_cm)) * frame.price_rise_rate * 100
넵 수정했어요!

2021-05-05 15:33 UTC, Kang-kyunghun requested changes

2021-05-05 15:33 UTC, Kang-kyunghun commented on orders/views.py
> +                            (art.height_cm, art.width_cm, frame.thickness_cm)
```suggestion
           price = lambda x, y, z, a : ((x + z) * (y + z) - (x * y)) * a* 100)
            frame_sizes_prices = [
                {
                    'size'  : frame.name,
                    'price' : price(art.height_cm, art.width_cm, frame.thickness_cm, frame.price_rise_rate)
```
람다 잘 사용해 주셨어요~~ 혹시 제가 바꾼 코드로도 동작한다면, 이편이 조금 더 가독성이 좋을 거 같습니다. 한 번 확인해 주세요.

2021-05-05 17:26 UTC, ulr0 commented on orders/views.py
> +                            (art.height_cm, art.width_cm, frame.thickness_cm)
감사합니당 수정했어요!

2021-05-06 00:19 UTC, Kang-kyunghun commented
LGTM~~!!

2021-05-06 00:20 UTC, merged