[19기 문희원] Add : GET AuctionView
wecode-bootcamp-korea/19-2nd-Younggulart-backend pull request #8
Opened 2021-04-30 10:52 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 예정된 오프라인 경매 정보 GET 기능 구현
		 
## 수정 사항들 자세한 내용
- URI 예시 : auctions?date=2021-5-6
- 아래 postman 결과입니다.
<img width="650" alt="Screen Shot 2021-04-30 at 7 52 13 PM" src="https://user-images.githubusercontent.com/63729090/116685582-9067d800-a9ed-11eb-9b1e-25ac0bacbb92.png">

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-30 15:03 UTC, Kang-kyunghun requested changes
list를 뿌리는 경우가 많은데, 혹시 select_related와 prefetch_related의 사용법을 아시나요? 이 두가지를 이용해 데이터 캐싱이 가능하고 더 효율적으로 데이터를 가져 올 수 있습니다. 위의 방법을 한 번 조사해 보고 적용해 보면 좋을 것 같습니다.

2021-04-30 15:03 UTC, Kang-kyunghun commented on bids/views.py
> +                    'duration'     : f'{str(auction.start_date)[:-3]} 부터 {str(auction.end_date)[:-3]}',
- 슬라이싱 하드 코딩 상수로 바꾸는 것은 어떠신가요?
- 중간에 부터라는 str이 있는데, 이 부분은 시작 날짜과 마지막 날짜를 주고 프론트에서 가공하는 것이 맞지 않나 생각 됩니다. 희원님 의견을 어떠신가요?

2021-05-01 01:52 UTC, moonimooni commented
> list를 뿌리는 경우가 많은데, 혹시 select_related와 prefetch_related의 사용법을 아시나요? 이 두가지를 이용해 데이터 캐싱이 가능하고 더 효율적으로 데이터를 가져 올 수 있습니다. 위의 방법을 한 번 조사해 보고 적용해 보면 좋을 것 같습니다.

넴 알겠습니다

2021-05-01 01:55 UTC, moonimooni commented on bids/views.py
> +                    'duration'     : f'{str(auction.start_date)[:-3]} 부터 {str(auction.end_date)[:-3]}',
- 그냥 슬라이싱하지 말고 strftime 메소드 써서 년월일시분 만 빼오도록 하겠습니다.
- 넵 그게 나을 거 같습니다. 수정하겠습니다~

2021-05-01 02:46 UTC, moonimooni commented
master에서 json git rm -> commit -> new branch -> commit  해서 커밋 두 개입니다~

2021-05-02 02:29 UTC, redsaumon commented on bids/tests.py
> +            auction_id = 1
희원님 좋습니다~
그런데 TestCase를 상속받은 경우, setUp()은 각각의 test_method가 실행될 때마다 실행됩니다.
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)

    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 setUp에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 setUpTestData를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 setUp에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2021-05-02 04:36 UTC, moonimooni commented on bids/tests.py
> +            auction_id = 1
호오.. 그런 방법이 있었군요. 꿀정보 감사드립니다. 써보고 수정해서 다시 올리겠습니다!

2021-05-02 06:45 UTC, Kang-kyunghun commented
- commit이 3개네요. master 수정 때문에 그런 것 같은데, rebase가 안 되나요? 월요일에 git 한 번 같이 볼게요~
- 캐싱 전 후의 쿼리 수 차이 확인해 보셨나요? 노션의 8주차에 쿼리 로깅하는 셋팅법 소개 되어 있습니다. 제가 보기에는 제대로 캐싱이 안 될 것 같은데, 로깅하면서 차이가 실제로 일어나는지 확인해 보세요.

2021-05-02 07:12 UTC, moonimooni commented
> * commit이 3개네요. master 수정 때문에 그런 것 같은데, rebase가 안 되나요? 월요일에 git 한 번 같이 볼게요~
> * 캐싱 전 후의 쿼리 수 차이 확인해 보셨나요? 노션의 8주차에 쿼리 로깅하는 셋팅법 소개 되어 있습니다. 제가 보기에는 제대로 캐싱이 안 될 것 같은데, 로깅하면서 차이가 실제로 일어나는지 확인해 보세요.

- 넵 master에서 rebase 하면 conflict가 해결이 안되어서 일단 진행중이었습니다. 일단 저도 한 번 더 만져보겠습니다!

- 쿼리 로그 수 찍어보면서 했습니다!
- 가장 로그가 많은 날짜 기준으로,
- 29 : select_related, prefetch_related 안했을때
- 28 : prefetch_related만 했을때
- 27 : select_related 만 했을때
- 26 : 둘 다 적용했을때

이렇게 찍힙니다!

2021-05-02 07:25 UTC, Kang-kyunghun commented
29개에서 26개가 찍혔다는 거죠?? 보통 잘 적용 했다면 단순히 리스트만 뿌리는 상황에서 쿼리를 10개 미만 최대 1개까지도 줄일 수 있습니다. 
이 PR은 내일 git 잠깐 같이 보고 다시 리뷰 진행 하겠습니다.

2021-05-02 07:26 UTC, moonimooni commented
> 29개에서 26개가 찍혔다는 거죠?? 보통 잘 적용 했다면 단순히 리스트만 뿌리는 상황에서 쿼리를 10개 미만 최대 1개까지도 줄일 수 있습니다.
> 이 PR은 내일 git 잠깐 같이 보고 다시 리뷰 진행 하겠습니다.

넵 알겠습니다~

2021-05-02 07:45 UTC, moonimooni commented
> 29개에서 26개가 찍혔다는 거죠?? 보통 잘 적용 했다면 단순히 리스트만 뿌리는 상황에서 쿼리를 10개 미만 최대 1개까지도 줄일 수 있습니다.
> 이 PR은 내일 git 잠깐 같이 보고 다시 리뷰 진행 하겠습니다.

아 그리고 git은 방금 마스터에서 reset 해서 해결했습니다!

2021-05-03 01:31 UTC, Kang-kyunghun commented
LGTM~~!!!!

2021-05-03 01:31 UTC, merged